name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to GitHub summary
        run: |
          echo "## Test Coverage" >> $GITHUB_STEP_SUMMARY
          coverage report -m --rcfile=.coveragerc >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
